services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile.prod
    container_name: vectorization-backend
    ports:
      - "8001:8000"

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile.prod
    container_name: vectorization-frontend
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8001
    ports:
      - "3100:3000"
