services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile.dev

    # ★ ホストの ./memos → コンテナ /app/memos
    volumes:
      - ../memos:/app/memos
      - ../memos/.index_data:/app/.index_data:rw
      # ソースもマウントしてホットリロード
      - ../apps/backend:/app

    environment:
      - PYTHONUNBUFFERED=1

    command:
      - uvicorn
      - main:app
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
      - --reload
      - --log-level
      - debug

    ports:
      - "8001:8000"

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile.dev

    volumes:
      - ../apps/frontend:/app
      - /app/node_modules

    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8001
    command: ["npm", "run", "dev"]
    ports:
      - "3100:3000"
